const String cat1 = "Hospital/ Health"; // c4
const String cat2 = "Restaurant Hotel"; //
const String cat3 = "Entertainment"; //
const String cat4 = "Retail and Shopping"; //
const String cat5 = "Transport"; //
const String cat6 = "Maintenance"; //

const String catim1 = "assets/images/categories/m1.jpeg"; //
const String catim2 = "assets/images/categories/m2.jpeg"; //
const String catim3 = "assets/images/categories/m3.jpeg"; //
const String catim4 = "assets/images/categories/m4.jpeg"; //
const String catim5 = "assets/images/categories/m5.jpeg"; //
const String catim6 = "assets/images/categories/m6.jpeg"; //
const String catim7 = "assets/images/categories/m7.jpeg"; //
const String catim8 = "assets/images/categories/m8.jpeg"; //
const String catim9 = "assets/images/categories/m9.jpeg"; //
const String catim10 = "assets/images/categories/m10.jpeg"; //
const String catim11 = "assets/images/categories/m11.jpeg"; //
const String catim12 = "assets/images/categories/m12.jpeg"; //
const String catim13 = "assets/images/categories/m13.jpeg"; //
const String catim14 = "assets/images/categories/m14.jpeg"; //
const String catim15 = "assets/images/categories/m15.jpeg"; //
const String catim16 = "assets/images/categories/m16.jpeg"; //
const String catim17 = "assets/images/categories/m17.jpeg"; //
const String catim18 = "assets/images/categories/m18.jpeg"; //
const String catim19 = "assets/images/categories/m19.jpeg"; //