// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeY7ShqlfbNty-pWyu891uFfFpUKHbDkY',
    appId: '1:187165842744:web:2e67fa88578a6ecc11f5cd',
    messagingSenderId: '187165842744',
    projectId: 'pondyapp-17bf4',
    authDomain: 'pondyapp-17bf4.firebaseapp.com',
    databaseURL: 'https://pondyapp-17bf4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondyapp-17bf4.appspot.com',
    measurementId: 'G-J6KP91F7D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76XvYZLffTiJKkI6B_t6rQIRBb-8mTQQ',
    appId: '1:187165842744:android:5056c9d12c1d536f11f5cd',
    messagingSenderId: '187165842744',
    projectId: 'pondyapp-17bf4',
    databaseURL: 'https://pondyapp-17bf4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondyapp-17bf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPsL-D2jExBrKYKwWbYrjvgHYac1K2ztM',
    appId: '1:187165842744:ios:35d34462a542b32611f5cd',
    messagingSenderId: '187165842744',
    projectId: 'pondyapp-17bf4',
    databaseURL: 'https://pondyapp-17bf4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondyapp-17bf4.appspot.com',
    androidClientId: '187165842744-jnc2aan2pp4lkji8pkde0d96njcv5l8d.apps.googleusercontent.com',
    iosClientId: '187165842744-hrgmgnlv92vi9nq19r0pmcuocnbi7c33.apps.googleusercontent.com',
    iosBundleId: 'com.example.pondyapp',
  );
}
